language: php

dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: PHPCS=1

install:
  - composer install
  - composer run-script post-install-cmd --no-interaction

script:
  - if [[ $PHPCS != 1 ]]; then phpunit; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=config/Migrations ./src ./tests ./config ./webroot; fi

notifications:
  email: false
